In [2]:
import numpy as np
import pandas as pd

In [3]:
#create 1 dimension array
arr_1D = np.array([1, 2, 3, 4, 5])
arr_1D

array([1, 2, 3, 4, 5])

In [6]:
type(arr_1D)

numpy.ndarray

In [9]:
#creating 2 dimenson
arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr_2D.shape

(2, 3)

In [15]:
arr_2D[0:2, 1:2]

array([[2],
       [5]])

In [18]:
arr_2D[:, 1]

array([2, 5])

In [26]:
#one of vales
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
#zero of vales
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Intro to DataFrame
1. Membuat dataframe dari:
    - List
    - Tuple
    - Numpy Array
    - Pandas Series
    
2. Membaca File menggunakan Datafreame:
    - csv
    - excel

In [31]:
#list
list1 =['Nasi Goreng', 'Bakso', "Vander'c Spinach"]
list2 = [10000, 22000, 55000]
list3 = ['Mampang', ' Lap Banteng', 'Monas']

zip(list1, list2, list3)

In [32]:
list(zip(list1, list2, list3))

[('Nasi Goreng', 10000, 'Mampang'),
 ('Bakso', 22000, ' Lap Banteng'),
 ("Vander'c Spinach", 55000, 'Monas')]

In [33]:
pd.DataFrame(list(zip(list1, list2, list3)))

0      1             2
0       Nasi Goreng  10000       Mampang
1             Bakso  22000   Lap Banteng
2  Vander'c Spinach  55000         Monas

In [37]:
df_list = pd.DataFrame(list(zip(list1, list2, list3)), columns=['Makanan', 'Harga', 'Lokasi'])
df_list

Makanan  Harga        Lokasi
0       Nasi Goreng  10000       Mampang
1             Bakso  22000   Lap Banteng
2  Vander'c Spinach  55000         Monas

In [38]:
type(df_list)

pandas.core.frame.DataFrame

In [40]:
display(type(df_list))

pandas.core.frame.DataFrame

In [42]:
display(df_list.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Makanan  3 non-null      object
 1   Harga    3 non-null      int64 
 2   Lokasi   3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes


None

In [46]:
# Tuple
tuple1 = ('Nasi Goreng', 10000, 'Mampang')
tuple2 = ('Bakso', 22000, 'Lap Banteng')
tuple3 = ("Vander'c Spinach", 55000, 'Monas')

df_tuple = pd.DataFrame([tuple1, tuple2, tuple3], columns=['Makanan', 'Harga', 'Lokasi'])
df_tuple

Makanan  Harga       Lokasi
0       Nasi Goreng  10000      Mampang
1             Bakso  22000  Lap Banteng
2  Vander'c Spinach  55000        Monas

In [47]:
display(df_tuple.info())
display(type(df_tuple))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Makanan  3 non-null      object
 1   Harga    3 non-null      int64 
 2   Lokasi   3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes


None

pandas.core.frame.DataFrame

In [69]:
df_array = pd.DataFrame(np.array([['Nasi Goreng', 10000, 'Mampang', 2.5, '23-10-2023'],
                         ['Bakso', 22000, 'Lap. Banteng', 4.0, '11-10-2023'],
                         ["Vander'c Spinach", 55000, 'Monas', 3.5, '20-11-2023']]),
                        columns=['Makanan', 'Harga', 'Lokasi', 'Rating', 'Tanggal Rating'])

df_array

Makanan  Harga        Lokasi Rating Tanggal Rating
0       Nasi Goreng  10000       Mampang    2.5     23-10-2023
1             Bakso  22000  Lap. Banteng    4.0     11-10-2023
2  Vander'c Spinach  55000         Monas    3.5     20-11-2023

In [70]:
display(df_array.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Makanan         3 non-null      object
 1   Harga           3 non-null      object
 2   Lokasi          3 non-null      object
 3   Rating          3 non-null      object
 4   Tanggal Rating  3 non-null      object
dtypes: object(5)
memory usage: 248.0+ bytes


None

In [71]:
df_array['Harga'] = df_array['Harga'].astype('int64')
df_array['Rating'] = df_array['Rating'].astype('float64')
df_array['Tanggal Rating'] = df_array['Tanggal Rating'].astype('datetime64[ns]')
df_array

Makanan  Harga        Lokasi  Rating Tanggal Rating
0       Nasi Goreng  10000       Mampang     2.5     2023-10-23
1             Bakso  22000  Lap. Banteng     4.0     2023-11-10
2  Vander'c Spinach  55000         Monas     3.5     2023-11-20

In [72]:
display(df_array.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   Makanan         3 non-null      object        
 1   Harga           3 non-null      int64         
 2   Lokasi          3 non-null      object        
 3   Rating          3 non-null      float64       
 4   Tanggal Rating  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 248.0+ bytes


None

In [75]:
series1 = pd.Series(['Nasi Goreng', 'Bakso', "Vander'c Spinach"])
series2 = pd.Series([10000, 22000, 55000])
series3 = pd.Series(['Mampang', ' Lap Banteng', 'Monas'])

df_series = pd.DataFrame({'Makanan':series1,
                         'Harga':series2,
                         'Lokasi':series3})
df_series

Makanan  Harga        Lokasi
0       Nasi Goreng  10000       Mampang
1             Bakso  22000   Lap Banteng
2  Vander'c Spinach  55000         Monas

In [76]:
df_series.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Makanan  3 non-null      object
 1   Harga    3 non-null      int64 
 2   Lokasi   3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes


In [79]:
list1 = ['Nasi Goreng', 'Bakso', "Vander'c Spinach"]
list2 = [10000, 22000, 55000]
list3 = ['Mampang', ' Lap Banteng', 'Monas']
list4 = pd.date_range('10-11-2023 03:00', periods = 3)

intermezo = pd.DataFrame(list(zip(list1, list2, list3, list4)),columns=['Makanan', 'Harga', 'Lokasi', 'Tanggal'])
intermezo

Makanan  Harga        Lokasi             Tanggal
0       Nasi Goreng  10000       Mampang 2023-10-11 03:00:00
1             Bakso  22000   Lap Banteng 2023-10-12 03:00:00
2  Vander'c Spinach  55000         Monas 2023-10-13 03:00:00

In [80]:
intermezo['Jam'] = pd.to_datetime(intermezo['Tanggal']).dt.time
intermezo['Hari'] = pd.to_datetime(intermezo['Tanggal']).dt.date
intermezo

Makanan  Harga        Lokasi             Tanggal       Jam  \
0       Nasi Goreng  10000       Mampang 2023-10-11 03:00:00  03:00:00   
1             Bakso  22000   Lap Banteng 2023-10-12 03:00:00  03:00:00   
2  Vander'c Spinach  55000         Monas 2023-10-13 03:00:00  03:00:00   

         Hari  
0  2023-10-11  
1  2023-10-12  
2  2023-10-13

In [81]:
intermezo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   Makanan  3 non-null      object        
 1   Harga    3 non-null      int64         
 2   Lokasi   3 non-null      object        
 3   Tanggal  3 non-null      datetime64[ns]
 4   Jam      3 non-null      object        
 5   Hari     3 non-null      object        
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 272.0+ bytes


In [84]:
#read csv from local
df =  pd.read_csv('/home/tyo/Downloads/Sample-Superstore-Orders.csv')
df.head(5)

Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
1       2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045   
3       4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   
4       5  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Row ID         9994 non-null   int64  
 1   Order ID       9994 non-null   object 
 2   Order Date     9994 non-null   object 
 3   Ship Date      9994 non-null   object 
 4   Ship Mode      9994 non-null   object 
 5   Customer ID    9994 non-null   object 
 6   Customer Name  9994 non-null   object 
 7   Segment        9994 non-null   object 
 8   Country        9994 non-null   object 
 9   City           9994 non-null   object 
 10  State          9994 non-null   object 
 11  Postal Code    9994 non-null   int64  
 12  Region         9994 non-null   object 
 13  Product ID     9994 non-null   object 
 14  Category       9994 non-null   object 
 15  Sub-Category   9994 non-null   object 
 16  Product Name   9994 non-null   object 
 17  Sales          9994 non-null   float64
 18  Quantity

In [87]:
#read csv from github
df_github = pd.read_csv('https://raw.githubusercontent.com/densaiko/data_science_learning/main/dataset/Sample-Superstore%20-%20Orders.csv')
df_github.head(2)

Row ID        Order ID Order Date   Ship Date     Ship Mode Customer ID  \
0       1  CA-2016-152156  11/8/2016  11/11/2016  Second Class    CG-12520   
1       2  CA-2016-152156  11/8/2016  11/11/2016  Second Class    CG-12520   

  Customer Name   Segment        Country       City  ... Postal Code  Region  \
0   Claire Gute  Consumer  United States  Henderson  ...       42420   South   
1   Claire Gute  Consumer  United States  Henderson  ...       42420   South   

        Product ID   Category Sub-Category  \
0  FUR-BO-10001798  Furniture    Bookcases   
1  FUR-CH-10000454  Furniture       Chairs   

                                        Product Name   Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.96         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.94         3   

   Discount    Profit  
0       0.0   41.9136  
1       0.0  219.5820  

[2 rows x 21 columns]

In [89]:
#excel file to read the tab/sheet
df_excel = pd.ExcelFile("/home/tyo/Downloads/Startups Data.xlsx")
df_excel.sheet_names

['Overview',
 'Financials',
 '1-500 with IDs',
 'Ben CSV Export',
 '1-1000',
 '1001-2000',
 '2001-3000',
 '3001-4000',
 '4001-5000']

In [90]:
df_exel = pd.read_excel("/home/tyo/Downloads/Startups Data.xlsx", sheet_name="Overview")
df_exel.head()

ID       Name     Industry  \
0   1   Over-Hex     Software   
1   2  Unimattax  IT Services   
2   3     Lexila  Real Estate   
3   4   Greenfax       Retail   
4   5     Saoace       Energy   

                                         Description  Year Founded  Employees  \
0  Provides a Web-based CRM tool that allows hosp...          2006         25   
1  Helps law firms use Thomson Reuters Elite prac...          2009         36   
2  Offers investment, construction, residential, ...          2013         38   
3  A Verizon Wireless premium retailer that offer...          2012        320   
4  An energy efficiency consulting firm that work...          2009         24   

  State            City    Metro Area  
0    TN        Franklin     Nashville  
1    PA  Newtown Square  Philadelphia  
2    IL     Tinley Park       Chicago  
3    SC      Greenville  Newberry, SC  
4    WI    New Holstein  Appleton, WI

In [7]:
data = {
    'name': ['Item{}'.format(i) for i in range(1000)],
    'type': ['Type{}'.format(i) for i in range(1000)],
    'calories': [i for i in range(1000)],
    'protein': [i * 2 for i in range(1000)],
    'fat': [i * 0.5 for i in range(1000)]
}

df = pd.DataFrame(data)

# Memilih bagian yang diminta
selected_df = df.loc[12:21, ['calories', 'protein', 'fat']]
selected_df

calories  protein   fat
12        12       24   6.0
13        13       26   6.5
14        14       28   7.0
15        15       30   7.5
16        16       32   8.0
17        17       34   8.5
18        18       36   9.0
19        19       38   9.5
20        20       40  10.0
21        21       42  10.5

In [8]:
df

name     type  calories  protein    fat
0      Item0    Type0         0        0    0.0
1      Item1    Type1         1        2    0.5
2      Item2    Type2         2        4    1.0
3      Item3    Type3         3        6    1.5
4      Item4    Type4         4        8    2.0
..       ...      ...       ...      ...    ...
995  Item995  Type995       995     1990  497.5
996  Item996  Type996       996     1992  498.0
997  Item997  Type997       997     1994  498.5
998  Item998  Type998       998     1996  499.0
999  Item999  Type999       999     1998  499.5

[1000 rows x 5 columns]

In [11]:
df.corr()

calories  protein  fat
calories       1.0      1.0  1.0
protein        1.0      1.0  1.0
fat            1.0      1.0  1.0

In [16]:
my_array = np.array([1,2,3,4,5,6,7])

In [26]:
my_array[1::2]

array([2, 4, 6])

In [39]:
arr = np.array([1,2,3,4,5,6,7])
arr[2:5]

array([3, 4, 5])